#Hugo configuration
title = "Google IMA Ads"
baseURL = "https:\/\/www.jeje.com"
languageCode = "en-us"
theme = "tvpage"
disablePathToLower = "true"
enableRobotsTXT = true

[params]
loginId = "1758397"
subfolder = ""
